Work around market exception:
java.lang.RuntimeException: Unable to resume activity
{com.kaitenmail/com.kaitenmail.activity.MessageList}:
java.lang.NullPointerException
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2227)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2255)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1769)
at android.app.ActivityThread.access$1500(ActivityThread.java:122)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1002)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:132)
at android.app.ActivityThread.main(ActivityThread.java:4025)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:491)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.kaitenmail.activity.MessageList$MessageListAdapter.updateForMe(MessageList.java:2617)
at com.kaitenmail.activity.MessageList$MessageListAdapter.access$5000(MessageList.java:2331)
at com.kaitenmail.activity.MessageList$MessageListAdapter$1.synchronizeMailboxStarted(MessageList.java:2343)
at com.kaitenmail.controller.MessagingController$MemorizingListener.refreshOther(MessagingController.java:4519)
at com.kaitenmail.controller.MessagingController.refreshListener(MessagingController.java:348)
at com.kaitenmail.controller.MessagingController.addListener(MessagingController.java:343)
at com.kaitenmail.activity.MessageList.onResume(MessageList.java:888)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1153)
at android.app.Activity.performResume(Activity.java:4428)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2217)
... 12 more